### ISSUE TITLE
Include abstract in rating calculation

### ISSUE THREAD

**Issue by Simske** [matiscke/scan_astro-ph#15]
With the new parsing implementation using the API (#14) the abstract is now also part of the `Entry` object and can therefore be easily scanned for keywords.

This brings up the question: does it make sense to introduce an weight factor between title and abstract? Keywords which occur in the title arguably carry more weight than an occurrence in the abstract.

An author weight could also be used, but the same effect can also be achieved by the user by setting the ratings of authors generally higher/lower than for keywords.

**Comment by matiscke** [comment]
I see the purpose behind such a weight; the downside is that it introduces complexity (for the user). Even if there is a default setting or if it is completely fixed, we would have to explain it. I find it valuable if the tool was as straightforward to use as possible.
