### ISSUE TITLE
only today's listings or those of a whole month can be shown

### ISSUE THREAD

**Issue by matiscke** [matiscke/scan_astro-ph#2]
what other listings are possible from the HTML listings on astro-ph? Can they be implemented?

**Comment by Simske** [comment]
How granular should this selection be?
With the API implementation (#14) we get the last n articles (we can choose the chunksize) ordered from newest to oldest. So we can pretty easily implement last day / last week / last month / last n days, by getting the next chunk until we hit the cutoff date.

**Comment by Simske** [comment]
Also: what should the default be?
The "new" page on ArXiv follows this schedule 
![20210609_234004](https://user-images.githubusercontent.com/2445660/121433354-30653980-c97c-11eb-9978-da1e9ae1e2c6.png)
[https://arxiv.org/help/availability](https://arxiv.org/help/availability).
I think it makes the most sense to replicate this

**Comment by matiscke** [comment]
> How granular should this selection be?
> With the API implementation (#14) we get the last n articles (we can choose the chunksize) ordered from newest to oldest. So we can pretty easily implement last day / last week / last month / last n days, by getting the next chunk until we hit the cutoff date.

I think "last day" would be a good default option. Then maybe options for "recent" (mirroring the "recent" listing of the Arxiv page) and "last n days"? I agree that "last week" and "last month" could also be useful for some users. If it's indeed little effort, we could go for it.
