### ISSUE TITLE
[enhancement] Using arxiv.org API or RSS feed instead of regex HTML parsing

### ISSUE THREAD

**Issue by Simske** [matiscke/scan_astro-ph#6]
Currently the astro-ph listings are queried on their HTML interface and "parsed" using regex. This seems fragile and error-prone, (this is slightly alleviated by the fact that the arxiv.org interface changes rarely, but still).

The better solution would be to use the [arxiv.org API](https://arxiv.org/help/api/basics) and/or the [RSS feeds](https://arxiv.org/help/rss).
The API result and RSS feeds have a clearly defined XML structure, which can be really parsed, and should contain the same information as the HTML. This should also make it easier to allow for the same functionality on other archives on arxiv.org other than astro-ph.

But the details of this are not yet clear to me, one would need to find the right API query or RSS feed to match the submissions shown on astro-ph recent (and etc.).
Maybe the [form interface](https://arxiv.org/form/astro-ph) is also useful for this, but we would need to find out if all form queries can be translated into API queries.

What are your thoughts on this?

**Comment by matiscke** [comment]
Yes I agree, this would definitely be a nice-to-have and would enable better functionality and stability. Since it would be a major rebuild, this wasn't tackled yet out of lack of time. Volunteered contributions are of course very welcome; I would be delighted to test&review a PR.

**Comment by matiscke** [comment]
@Simske one of the [most pressing issues](https://github.com/matiscke/scan_astro-ph/issues/1) I see is that in the current "parsing mode", all papers on the whole page (_including resubmissions and cross-refs_) are printed. Unfortunately, my regex skills are way insufficient to try and filter for those unwanted entries...

Did you get a chance to look into arxive's API or RSS feeds yet? I think this could be more elegantly solved that way.

Besides, I think working with the API would make it much easier to resolve https://github.com/matiscke/scan_astro-ph/issues/2.

**Comment by Simske** [comment]
I didn't look further into the API / RSS yet, but the issue of ignoring resubmissions and cross-lists can be easily fixed with the regex parsing.

I will submit a PR in a few minutes
