### ISSUE TITLE
[refactor] Python 2 support, dependencies, code structure

### ISSUE THREAD

**Issue by Simske** [matiscke/scan_astro-ph#7]
While looking over the code, a few things caught my eye, but I didn't want to open an issue for each of these, so here they are all in one:
- Some parts of the code try to be compatible with both Python 3 and Python 2 (e.g. future imports in `scan_astroph.py`). Should this package be compatible with Python 2? In my opinion this is not necessary, considering Python 2 maintainance has ended on 2020-01-01. 
- For CLI argument parsing the [deprecated module `optparse`](https://docs.python.org/3/library/optparse.html?highlight=optparse#module-optparse) is used, this should be switched to the newer [`argparse`](https://docs.python.org/3/library/argparse.html#module-argparse) (also in the Python standard library). The interface is very similar, and should be fast to switch
- Instead of the manual `debug_print` function, the logging module could be used, coupled with a verbosity argument on the CLI (`-v`, `-vv`, `-vvv` depending on log level)
- For colored output in the terminal the package [`termcolor`](https://pypi.org/project/termcolor/) is used. The last release of `termcolor` is from 2011, maybe there are more up to date packages out there (or not, I haven't checked yet).  
  Also: I haven't declared termcolor a dependency in the package installer (#5), this should be done when this is resolved.
- It can be nice to have a consistent code style in the project, I personally use the [black](https://github.com/psf/black) as formatter and [isort](https://pycqa.github.io/isort/) for import sorting.  
  To enforce this on the repository the tool [pre-commit](https://pre-commit.com/) can be used, which can run black and isort (and others) on commit (if the user installs it), and can also be configured with Github actions.

Obviously I don't want to step on anyone's toes, these were just some observations I made.

Not all of these need to be addressed, but I thought I just throw this out there to see what your thoughts on this are.

I am happy to work on any/all of them, most of them don't require a lot of work (and have nothing to do with functionality).

**Comment by matiscke** [comment]
I think it's fair to say that all of these issues fall under the category "for historical reasons" and could be modified to more up-to-date approaches. 

As for formatting the code style, some inner voice tells me "never touch a running system", but I might be old-fashioned.
